In [1]:
import pandas as pd

# Load Data:

## Players:

In [2]:
players_master = pd.read_csv("data/2024-2025/players/players.csv")
print(players_master.shape)
players_master.head(3)

(804, 7)

,player_code,player_id,first_name,second_name,web_name,team_id,position
0,438098,1,Fábio,Ferreira Vieira,Fábio Vieira,3,Midfielder
1,100051017,735,Mikel,Arteta,Arteta,3,Unknown
2,616059,756,Jack,Porter,Porter,3,Goalkeeper

In [16]:
players_master.position.value_counts()

position
Midfielder    347
Defender      268
Forward        87
Goalkeeper     82
Unknown        20
Name: count, dtype: int64

## Player Stats:

In [7]:
player_stats = pd.read_csv("data/2024-2025/playerstats/playerstats.csv")
print(player_stats.shape)
player_stats.head(3)

(27657, 58)

,id,status,chance_of_playing_next_round,chance_of_playing_this_round,now_cost,now_cost_rank,now_cost_rank_type,cost_change_event,cost_change_event_fall,cost_change_start,...,threat_rank,threat_rank_type,ict_index,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,direct_freekicks_order,penalties_order,gw,set_piece_threat
0,5,u,0.0,0.0,4.0,645,55,0,0,0,...,512,31,0.0,566,63,NaN,NaN,NaN,23,NaN
1,6,a,100.0,100.0,5.6,100,10,0,0,1,...,130,14,66.0,136,35,NaN,NaN,NaN,23,NaN
2,7,a,100.0,100.0,4.7,323,209,0,0,-3,...,421,221,10.4,384,187,NaN,NaN,NaN,23,NaN

In [13]:
player_stats.columns.values

array(['id', 'status', 'chance_of_playing_next_round',
       'chance_of_playing_this_round', 'now_cost', 'now_cost_rank',
       'now_cost_rank_type', 'cost_change_event',
       'cost_change_event_fall', 'cost_change_start',
       'cost_change_start_fall', 'selected_by_percent', 'selected_rank',
       'selected_rank_type', 'total_points', 'event_points',
       'points_per_game', 'points_per_game_rank',
       'points_per_game_rank_type', 'bonus', 'bps', 'form', 'form_rank',
       'form_rank_type', 'value_form', 'value_season', 'dreamteam_count',
       'transfers_in', 'transfers_in_event', 'transfers_out',
       'transfers_out_event', 'ep_next', 'ep_this', 'expected_goals',
       'expected_assists', 'expected_goal_involvements',
       'expected_goals_conceded', 'expected_goals_per_90',
       'expected_assists_per_90', 'expected_goal_involvements_per_90',
       'expected_goals_conceded_per_90', 'influence', 'influence_rank',
       'influence_rank_type', 'creativity', 'creativity_rank',
       'creativity_rank_type', 'threat', 'threat_rank',
       'threat_rank_type', 'ict_index', 'ict_index_rank',
       'ict_index_rank_type', 'corners_and_indirect_freekicks_order',
       'direct_freekicks_order', 'penalties_order', 'gw',
       'set_piece_threat'], dtype=object)

## Team Stats:

In [8]:
team_stats = pd.read_csv("data/2024-2025/teams/teams.csv")
print(team_stats.shape)
team_stats.head(3)

(20, 13)

,code,id,name,short_name,strength,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id,elo
0,3,1,Arsenal,ARS,5,1350,1350,1390,1400,1310,1300,1,1991
1,7,2,Aston Villa,AVL,3,1145,1240,1130,1180,1160,1300,2,1870
2,91,3,Bournemouth,BOU,3,1170,1200,1120,1180,1220,1220,127,1806

# Weekly Stats:

## Players - Match Stats:

In [4]:
players_matches = pd.read_csv("data/2024-2025/playermatchstats/GW1/playermatchstats.csv")
print(players_matches.shape)
players_matches.head(3)

(245, 50)

,match_id,match_url,player_id,minutes_played,goals,assists,total_shots,xg,xa,xgot,...,successful_dribbles_percent,saves,goals_conceded,xgot_faced,goals_prevented,sweeper_actions,high_claim,gk_accurate_long_balls,gk_accurate_passes,offsides
0,24-25-prem-arsenal-vs-wolverhampton-wanderers,/matches/wolverhampton-wanderers-vs-arsenal/2t...,17,80.0,1.0,1.0,5.0,0.35,0.37,0.50,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,24-25-prem-arsenal-vs-wolverhampton-wanderers,/matches/wolverhampton-wanderers-vs-arsenal/2t...,4,90.0,1.0,1.0,5.0,0.45,0.04,0.73,...,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24-25-prem-arsenal-vs-wolverhampton-wanderers,/matches/wolverhampton-wanderers-vs-arsenal/2t...,15,90.0,0.0,0.0,0.0,0.00,0.00,0.00,...,NaN,3.0,0.0,0.19,0.19,0.0,1.0,5.0,23.0,NaN

In [14]:
players_matches.columns.values

array(['match_id', 'match_url', 'player_id', 'minutes_played', 'goals',
       'assists', 'total_shots', 'xg', 'xa', 'xgot', 'shots_on_target',
       'successful_dribbles', 'big_chances_missed',
       'touches_opposition_box', 'touches', 'accurate_passes',
       'accurate_passes_percent', 'chances_created', 'final_third_passes',
       'accurate_crosses', 'accurate_crosses_percent',
       'accurate_long_balls', 'accurate_long_balls_percent',
       'tackles_won', 'tackles_won_percent', 'tackles', 'interceptions',
       'recoveries', 'blocks', 'clearances', 'headed_clearances',
       'dribbled_past', 'duels_won', 'duels_lost', 'ground_duels_won',
       'ground_duels_won_percent', 'aerial_duels_won',
       'aerial_duels_won_percent', 'was_fouled', 'fouls_committed',
       'successful_dribbles_percent', 'saves', 'goals_conceded',
       'xgot_faced', 'goals_prevented', 'sweeper_actions', 'high_claim',
       'gk_accurate_long_balls', 'gk_accurate_passes', 'offsides'],
      dtype=object)

## Matches:

In [18]:
matches = pd.read_csv("data/2024-2025/matches/GW1/matches.csv")
print(matches.shape)
matches.head(3)

(10, 102)

,gameweek,kickoff_time,home_team,home_team_elo,home_score,away_score,away_team,away_team_elo,finished,match_id,...,away_aerial_duels_won,home_aerial_duels_won_pct,away_aerial_duels_won_pct,home_successful_dribbles,away_successful_dribbles,home_successful_dribbles_pct,away_successful_dribbles_pct,fotmob_id,stats_processed,player_stats_processed
0,1,2024-08-17T14:00:00,11,1706.85,0.0,3.0,36,1713.16,True,24-25-prem-everton-vs-brighton-&-hove-albion,...,13.0,58.0,42.0,5.0,6.0,31.0,33.0,4506266,True,True
1,1,2024-08-16T19:00:00,1,1779.04,1.0,0.0,54,1716.28,True,24-25-prem-manchester-united-vs-fulham,...,16.0,54.0,46.0,8.0,8.0,42.0,40.0,4506263,True,True
2,1,2024-08-17T14:00:00,3,1946.90,2.0,0.0,39,1677.86,True,24-25-prem-arsenal-vs-wolverhampton-wanderers,...,13.0,57.0,43.0,9.0,8.0,47.0,50.0,4506265,True,True

# Linking Players and Matches:

In [26]:
def player_info(player_id):
    """
    Returns a dictionary of information for a given player.
    """
    player = players_master[players_master["player_id"] == player_id]
    if player.empty:
        return None
    return player.iloc[0].to_dict()

In [29]:
print(player_info(1))
id_1_player = player_info(1)
print(id_1_player['position'])  # Example usage to get position

{'player_code': 438098, 'player_id': 1, 'first_name': 'Fábio', 'second_name': 'Ferreira Vieira', 'web_name': 'Fábio Vieira', 'team_id': 3, 'position': 'Midfielder'}
Midfielder